# Containers written by an older Myrkr must still open.
#
# WHY THIS FILE EXISTS AT ALL, AND WHY IT WAS WRITTEN BEFORE THE CODE IT GUARDS:
#
# The container header carries a version, and every reader in the tree compares
# it for EXACT equality - `cmp dword ptr [r10+4], HDR_VERSION / jne corrupt`, in
# four places. So the moment HDR_VERSION is bumped, every container anyone
# already has stops opening, and the message they get is "not a valid Myrkr
# container", i.e. the tool tells them their data is corrupt.
#
# Phase B of docs/V5_WORK.md bumps it (segments, for entries past 64 GiB). Its
# plan says the old format "stays readable forever and gets a fixture in the
# suite that is never regenerated". That fixture CANNOT BE MADE AFTER THE BUMP -
# once the writer emits the new version there is nothing left that can produce
# the old one, and the compatibility claim becomes untestable forever. So the
# fixtures were frozen first, at 1.0.72, while the writer could still make them.
#
# tests/fixtures/v6-*.mrk are those files. They are checked in as binaries and
# they are NEVER REGENERATED. If a change makes this test fail, the change is
# what is wrong - not the fixture. tools/make_v6_fixtures.ps1 records exactly how
# they were produced, and is kept for provenance, not for re-running.
#
# Today this passes trivially: the current writer still writes version 6, so the
# reader is reading its own output. That is the point. It is in place, green, and
# committed BEFORE the bump, so the day the bump lands it becomes the only thing
# standing between a version number and everyone's archives.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$exe  = Join-Path $root "bin\myrkr.exe"
$fix  = Join-Path $PSScriptRoot "fixtures"
$w    = Join-Path $env:TEMP "myrkr_compattest"
$PW   = "Fixture-Horse-Battery-9"
$fail = 0

# The content that went in, by SHA-256. Recorded here rather than alongside the
# fixtures so that a regenerated fixture cannot quietly bring a matching hash
# with it.
$WANT = @{
    "a.txt"     = "37FD292DB97C3D86F9BDAC78C79CCA3350F71AF6C134846A519E5FBB4EF6314F"
    "b.txt"     = "EB74C1F8E6588AA4AFA080C00A1CBB7FE22A7869E261F0F9F548731E8DF5D19B"
    "empty.bin" = "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"
    "rand.bin"  = "3710368179E973D3703CCAC8A0D932D39C27169ACDDB08625CDD9E1D03E4986C"
}
$WANT_ONE = "DADB9A8DFB3E6C18035B14F89A6A7931C9E5EC8259D53ECAFA57B64A56387AEF"
$FIX_VERSION    = 6       # what these fixtures were written by
$WRITER_VERSION = 8       # what this build writes (HDR_VERSION)
$MIN_VERSION    = 6       # the oldest it reads (HDR_VERSION_MIN)

"building dbg (decrypt is refused on the command line in release)..."
$blog = cmd /c "$root\build.cmd dbg" 2>&1
if (($blog -join "`n") -notmatch "BUILD OK") { "FAIL build"; $blog | Select-Object -Last 15; exit 1 }

if (Test-Path $w) { [IO.Directory]::Delete($w, $true) }
New-Item -ItemType Directory -Path $w | Out-Null

function Run([string[]]$a) {
    $q = ($a | ForEach-Object { '"' + $_ + '"' }) -join ' '
    $o = cmd /c "`"$exe`" $q 2>&1"
    return [pscustomobject]@{ rc = $LASTEXITCODE; out = (($o | Out-String) -replace "`r", "") }
}

# ---- 0. the fixtures are what they claim to be ----------------------------
# A fixture regenerated by a newer writer would still decrypt, and this test
# would still pass while proving nothing at all. So check the version byte on
# disk first: these files must stay at version 6 forever.
foreach ($n in @("v6-archive-store.mrk","v6-archive-comp.mrk","v6-bare-store.mrk","v6-bare-comp.mrk")) {
    $b = [IO.File]::ReadAllBytes((Join-Path $fix $n))
    $magic = [Text.Encoding]::ASCII.GetString($b, 0, 4)
    $ver   = [BitConverter]::ToUInt32($b, 4)
    if ($magic -ne "MYRK" -or $ver -ne $FIX_VERSION) {
        "  FAIL $n is magic=$magic version=$ver - it has been REGENERATED. Restore it from git; it is not meant to move."
        $fail++
    }
}
# Version 8 is frozen too, and for a reason the version-6 set does not cover.
# The AAD length became version-dependent at 8 (header || ordinal || segment,
# 92 bytes, against 88 before it). A change to the SHORT form is caught by the
# v6 fixtures. A change to the LONG form is invisible to a round-trip, because
# this build is both the writer and the reader and would simply agree with
# itself - so it needs a file written before the change to disagree with.
#
# There is deliberately no version-7 fixture. Version 7 was byte-identical to 6
# and shares its AAD length, so the v6 set exercises the same path; nothing was
# lost by 7 never being frozen.
foreach ($n in @("v8-archive-store.mrk","v8-archive-comp.mrk")) {
    $b = [IO.File]::ReadAllBytes((Join-Path $fix $n))
    $ver = [BitConverter]::ToUInt32($b, 4)
    if ([Text.Encoding]::ASCII.GetString($b,0,4) -ne "MYRK" -or $ver -ne 8) {
        "  FAIL $n is version=$ver - it has been REGENERATED. Restore it from git."
        $fail++
    }
}
# part001 carries a 32-byte MVOL header before the container header.
$b = [IO.File]::ReadAllBytes((Join-Path $fix "v6-set.part001.mrk"))
if ([Text.Encoding]::ASCII.GetString($b,32,4) -ne "MYRK" -or [BitConverter]::ToUInt32($b,36) -ne $FIX_VERSION) {
    "  FAIL v6-set.part001.mrk has been regenerated"; $fail++
} else {
    "  ok   all five fixtures are still version $FIX_VERSION on disk"
}

# ---- 1. every kind of container the format can hold ------------------------
function CheckTree([string]$label, [string]$mrk, [string]$sub) {
    $out = Join-Path $w $label
    $r = Run @("decrypt", $mrk, "-o", $out, "-p", $PW)
    if ($r.rc -ne 0) { "  FAIL $label did not open (exit $($r.rc)): $($r.out)"; $script:fail++; return }
    $got = @{}
    Get-ChildItem -Recurse -File (Join-Path $out $sub) | ForEach-Object {
        $got[$_.Name] = (Get-FileHash $_.FullName).Hash
    }
    $bad = @()
    foreach ($k in $WANT.Keys) {
        if (-not $got.ContainsKey($k)) { $bad += "$k missing" }
        elseif ($got[$k] -ne $WANT[$k]) { $bad += "$k differs" }
    }
    if ($got.Count -ne $WANT.Count) { $bad += "$($got.Count) files, expected $($WANT.Count)" }
    if ($bad.Count) { "  FAIL $label : $($bad -join '; ')"; $script:fail++ }
    else { "  ok   $label opens and every file is byte-identical" }
}
function CheckOne([string]$label, [string]$mrk) {
    $out = Join-Path $w "$label.txt"
    $r = Run @("decrypt", $mrk, "-o", $out, "-p", $PW)
    if ($r.rc -ne 0) { "  FAIL $label did not open (exit $($r.rc)): $($r.out)"; $script:fail++; return }
    if ((Get-FileHash $out).Hash -ne $WANT_ONE) { "  FAIL $label decrypted to different bytes"; $script:fail++ }
    else { "  ok   $label opens and is byte-identical" }
}

CheckTree "archive-store" (Join-Path $fix "v6-archive-store.mrk") "tree"
CheckTree "archive-comp"  (Join-Path $fix "v6-archive-comp.mrk")  "tree"
CheckOne  "bare-store"    (Join-Path $fix "v6-bare-store.mrk")
CheckOne  "bare-comp"     (Join-Path $fix "v6-bare-comp.mrk")
# Handed a MEMBER of the set, not part 1: that is what proves a set is assembled
# from the part headers rather than from the name it was given.
CheckTree "volume-set"    (Join-Path $fix "v6-set.part002.mrk") "tree"
# The version-8 pair, whose entries were sealed under the LONGER AAD.
CheckTree "v8-store"      (Join-Path $fix "v8-archive-store.mrk") "tree"
CheckTree "v8-comp"       (Join-Path $fix "v8-archive-comp.mrk")  "tree"

# ---- 2. and it can still be listed, not just extracted ---------------------
$r = Run @("list", (Join-Path $fix "v6-archive-store.mrk"), "-p", $PW)
if ($r.rc -ne 0 -or $r.out -notmatch "rand\.bin") { "  FAIL the inventory of a v6 container did not list"; $fail++ }
else { "  ok   its inventory still lists" }

# ---- 2a. the writer has actually moved on ---------------------------------
# Without this, everything below passes just as well when the writer never left
# the old version - which is the shape of a "compatibility" test that is really
# only reading its own output. The whole value of the range is that the two ends
# are different, so the test has to know they are.
$mine = Join-Path $w "written-now.mrk"
New-Item -ItemType Directory -Path (Join-Path $w "src") | Out-Null
[IO.File]::WriteAllText((Join-Path $w "src\x.txt"), "written by this build")
$r = Run @("encrypt", (Join-Path $w "src"), "-o", $mine, "-p", $PW, "--store", "-m", "32", "-t", "1")
if ($r.rc -ne 0) {
    "  FAIL could not write a container with this build: $($r.out)"; $fail++
} else {
    $v = [BitConverter]::ToUInt32([IO.File]::ReadAllBytes($mine), 4)
    if ($v -ne $WRITER_VERSION) {
        "  FAIL this build writes format version $v, expected $WRITER_VERSION"; $fail++
    } elseif ($v -eq $FIX_VERSION) {
        "  FAIL the writer is still on the fixtures version - the range is untested"; $fail++
    } else {
        "  ok   this build writes version $v and reads $FIX_VERSION too - both ends live"
    }
}

# ---- 2b. a version it cannot read is not "corrupt" -------------------------
# The other half of the same problem. Once a bump lands, someone WILL hand this
# build a container from a different format version, and being told the file is
# damaged sends them looking for a backup they do not need.
$vN = Join-Path $w "wrongversion.mrk"
$bytes = [IO.File]::ReadAllBytes((Join-Path $fix "v6-archive-store.mrk"))
$bytes[4] = 9                                    # a version this build cannot read
[IO.File]::WriteAllBytes($vN, $bytes)
$r = Run @("list", $vN, "-p", $PW)
if ($r.rc -eq 0) { "  FAIL a container from another format version was accepted"; $fail++ }
elseif ($r.out -notmatch "format version 9" -or $r.out -notmatch "not damaged") {
    "  FAIL it was refused as corrupt rather than as a version mismatch: $($r.out)"; $fail++
} else {
    "  ok   another format version says so, and says the file is not damaged (exit $($r.rc))"
}
# Below the range as well as above it. An older container is the case that will
# actually happen, and it must be refused with the same sentence rather than
# falling through a path that only ever checked the upper end.
$vO = Join-Path $w "tooold.mrk"
$bytes = [IO.File]::ReadAllBytes((Join-Path $fix "v6-archive-store.mrk"))
$bytes[4] = $MIN_VERSION - 1
[IO.File]::WriteAllBytes($vO, $bytes)
$r = Run @("list", $vO, "-p", $PW)
if ($r.rc -eq 0) { "  FAIL a container older than the range was accepted"; $fail++ }
elseif ($r.out -notmatch "not damaged") { "  FAIL an older container was reported as corrupt: $($r.out)"; $fail++ }
else { "  ok   older than the range is refused the same way (exit $($r.rc))" }

# ...and a genuinely broken one must still say corrupt, or the distinction is
# worthless in the other direction.
$vB = Join-Path $w "brokenmagic.mrk"
$bytes = [IO.File]::ReadAllBytes((Join-Path $fix "v6-archive-store.mrk"))
$bytes[1] = 0x5A                                 # magic is no longer "MYRK"
[IO.File]::WriteAllBytes($vB, $bytes)
$r = Run @("list", $vB, "-p", $PW)
if ($r.rc -eq 0 -or $r.out -match "format version") {
    "  FAIL a corrupt container was reported as a version mismatch: $($r.out)"; $fail++
} else {
    "  ok   a corrupt one still reports corrupt (exit $($r.rc))"
}

# ---- 3. and verified without being written out -----------------------------
$r = Run @("verify", (Join-Path $fix "v6-archive-comp.mrk"), "-p", $PW)
if ($r.rc -ne 0) { "  FAIL verify rejected a good v6 container"; $fail++ }
else { "  ok   verify still authenticates one" }

""
"=== Restore: shipping build ==="
$blog = cmd /c "$root\build.cmd strict release" 2>&1
if (($blog -join "`n") -notmatch "BUILD OK") { "  FAIL could not restore the release build"; $fail++ }
else { "  bin\myrkr.exe is a release build - ok" }

if (Test-Path $w) { [IO.Directory]::Delete($w, $true) }

# =============================================================================
# MUTATION - applied, run, and the stated check observed to fail.
#
#   macros.inc: HDR_VERSION 6 -> 7, which is literally what phase B does.
#     -> every check in section 1 FAILS with exit 4 ("not a valid Myrkr
#        container"), and section 0 still passes - the fixtures are untouched,
#        it is the reader that stopped accepting them. That is the whole
#        failure this file exists to make impossible to ship unnoticed, and it
#        is exactly what will happen the moment phase B bumps the version
#        without adding the dispatch to go with it.
#
#   pack.asm / cmd.asm: route ir_version and oc_version back to ir_corrupt and
#   oc_corrupt, i.e. undo the version-mismatch message.
#     -> "another format version says so" FAILS: the container is reported as
#        corrupt, which is what it said before 1.0.73.
#
#   macros.inc: HDR_VERSION_MIN 6 -> 7, i.e. drop support for the old format.
#     -> every check in section 1 FAILS, this time with the version message
#        rather than with "corrupt" - the 1.0.74 shape of the same disaster, and
#        the reason MIN is a constant somebody has to move deliberately.
#
#   pack.asm, entry_stream_open: replace `jb eso_len` with `jmp eso_len`'s
#   opposite - i.e. put the segment in the AAD for EVERY version.
#     -> every version-6 check FAILS with exit 3 (authentication failed): their
#        entries were sealed over 88 bytes of AAD and are now being read over
#        92. The mirror image - never adding the segment - is invisible to a
#        round-trip and is what the v8 fixtures are frozen for.
#
#   macros.inc: HDR_VERSION 8 -> 7, i.e. the writer never moved on.
#     -> "this build writes version 7" FAILS. Everything else still passes,
#        which is exactly why that check is there: a build that had quietly lost
#        the new version would otherwise look perfectly healthy.
# =============================================================================
if ($fail -gt 0) { "$fail FAILURE(S)"; exit 1 } else { "compattest: all checks passed"; exit 0 }
